artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/7641fcd8adac4a0ba0123dfa75beafce/artifacts
end_time: 1774815802087
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: 7641fcd8adac4a0ba0123dfa75beafce
run_name: eval::holdout_paraphrases.jsonl
run_uuid: 7641fcd8adac4a0ba0123dfa75beafce
source_name: ''
source_type: 4
source_version: ''
start_time: 1774815801624
status: 3
tags: []
user_id: Vinay
