artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/b79e04a64bdc48fe9e4db0e2baf8346f/artifacts
end_time: 1774817150276
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: b79e04a64bdc48fe9e4db0e2baf8346f
run_name: eval::holdout_paraphrases.jsonl
run_uuid: b79e04a64bdc48fe9e4db0e2baf8346f
source_name: ''
source_type: 4
source_version: ''
start_time: 1774817149858
status: 3
tags: []
user_id: Vinay
