artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/6c62d273c2ad4afaa01caad190517a41/artifacts
end_time: 1774813408951
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: 6c62d273c2ad4afaa01caad190517a41
run_name: eval::holdout_paraphrases.jsonl
run_uuid: 6c62d273c2ad4afaa01caad190517a41
source_name: ''
source_type: 4
source_version: ''
start_time: 1774813408490
status: 3
tags: []
user_id: Vinay
