artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/bbde5cd5fe134727b095b53df7013fd0/artifacts
end_time: 1774813310267
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: bbde5cd5fe134727b095b53df7013fd0
run_name: eval::manual.jsonl
run_uuid: bbde5cd5fe134727b095b53df7013fd0
source_name: ''
source_type: 4
source_version: ''
start_time: 1774813309814
status: 3
tags: []
user_id: Vinay
