artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/6cf27eff35494ef5832927cc751deccd/artifacts
end_time: 1774810027448
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: 6cf27eff35494ef5832927cc751deccd
run_name: eval::holdout_paraphrases.jsonl
run_uuid: 6cf27eff35494ef5832927cc751deccd
source_name: ''
source_type: 4
source_version: ''
start_time: 1774810027028
status: 3
tags: []
user_id: Vinay
