artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/422338888089732488/2943b67787ee46d5aca94bef5f8246f4/artifacts
end_time: 1774810183367
entry_point_name: ''
experiment_id: '422338888089732488'
lifecycle_stage: active
run_id: 2943b67787ee46d5aca94bef5f8246f4
run_name: phase_gate::synthetic_scaffold_dataset_refined.jsonl
run_uuid: 2943b67787ee46d5aca94bef5f8246f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1774810182889
status: 3
tags: []
user_id: Vinay
