artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/bb83fa81d90b40b3b049b8eac3160be5/artifacts
end_time: 1774815729760
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: bb83fa81d90b40b3b049b8eac3160be5
run_name: eval::manual.jsonl
run_uuid: bb83fa81d90b40b3b049b8eac3160be5
source_name: ''
source_type: 4
source_version: ''
start_time: 1774815729237
status: 3
tags: []
user_id: Vinay
