artifact_location: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/422338888089732488
creation_time: 1774807411463
experiment_id: '422338888089732488'
last_update_time: 1774807411463
lifecycle_stage: active
name: eka-phase-gate
