artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/b8ad6cbab11742cfb298083fbba7589e/artifacts
end_time: 1774816151806
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: b8ad6cbab11742cfb298083fbba7589e
run_name: eval::holdout_paraphrases.jsonl
run_uuid: b8ad6cbab11742cfb298083fbba7589e
source_name: ''
source_type: 4
source_version: ''
start_time: 1774816151493
status: 3
tags: []
user_id: Vinay
