artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/422338888089732488/77af7e05ffdf4f63ae07f371244ce378/artifacts
end_time: 1774816266658
entry_point_name: ''
experiment_id: '422338888089732488'
lifecycle_stage: active
run_id: 77af7e05ffdf4f63ae07f371244ce378
run_name: phase_gate::synthetic_scaffold_dataset_refined.jsonl
run_uuid: 77af7e05ffdf4f63ae07f371244ce378
source_name: ''
source_type: 4
source_version: ''
start_time: 1774816265991
status: 3
tags: []
user_id: Vinay
