artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/eab34dcf4a0642039667f2e70e8b0d0a/artifacts
end_time: 1774810235352
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: eab34dcf4a0642039667f2e70e8b0d0a
run_name: eval::holdout_paraphrases.jsonl
run_uuid: eab34dcf4a0642039667f2e70e8b0d0a
source_name: ''
source_type: 4
source_version: ''
start_time: 1774810234931
status: 3
tags: []
user_id: Vinay
