artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/897debc2de624e5fb1ad78ee1794ec51/artifacts
end_time: 1774817120791
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: 897debc2de624e5fb1ad78ee1794ec51
run_name: eval::synthetic_scaffold_dataset_refined.jsonl
run_uuid: 897debc2de624e5fb1ad78ee1794ec51
source_name: ''
source_type: 4
source_version: ''
start_time: 1774817120409
status: 3
tags: []
user_id: Vinay
