artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/422338888089732488/064255a47e0b410aa70bede7056138cd/artifacts
end_time: 1774817229830
entry_point_name: ''
experiment_id: '422338888089732488'
lifecycle_stage: active
run_id: 064255a47e0b410aa70bede7056138cd
run_name: phase_gate::synthetic_scaffold_dataset_refined.jsonl
run_uuid: 064255a47e0b410aa70bede7056138cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1774817229225
status: 3
tags: []
user_id: Vinay
