artifact_location: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092
creation_time: 1774807394240
experiment_id: '143056074785624092'
last_update_time: 1774807394240
lifecycle_stage: active
name: eka-eval
