artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/422338888089732488/d3b6ea4969ac41adbbf0e651491f8698/artifacts
end_time: 1774807412074
entry_point_name: ''
experiment_id: '422338888089732488'
lifecycle_stage: active
run_id: d3b6ea4969ac41adbbf0e651491f8698
run_name: phase_gate::holdout_paraphrases.jsonl
run_uuid: d3b6ea4969ac41adbbf0e651491f8698
source_name: ''
source_type: 4
source_version: ''
start_time: 1774807411861
status: 3
tags: []
user_id: Vinay
