artifact_location: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/621317228279702369
creation_time: 1775097484762
experiment_id: '621317228279702369'
last_update_time: 1775097484762
lifecycle_stage: active
name: eka-eval
