artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/bc5dae3ad7584ac8b312212ce6ace222/artifacts
end_time: 1774807395400
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: bc5dae3ad7584ac8b312212ce6ace222
run_name: eval::holdout_paraphrases.jsonl
run_uuid: bc5dae3ad7584ac8b312212ce6ace222
source_name: ''
source_type: 4
source_version: ''
start_time: 1774807394806
status: 3
tags: []
user_id: Vinay
