artifact_uri: file:///C:/Users/Vinay/OneDrive/Desktop/enterprise-knowledge-assistant/artifacts/mlflow/143056074785624092/5976a3b53b434ad5991bea87d4edd80b/artifacts
end_time: 1774816262841
entry_point_name: ''
experiment_id: '143056074785624092'
lifecycle_stage: active
run_id: 5976a3b53b434ad5991bea87d4edd80b
run_name: eval::synthetic_scaffold_dataset_refined.jsonl
run_uuid: 5976a3b53b434ad5991bea87d4edd80b
source_name: ''
source_type: 4
source_version: ''
start_time: 1774816262469
status: 3
tags: []
user_id: Vinay
